// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://feenvxkkmnetknbthopq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZlZW52eGtrbW5ldGtuYnRob3BxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2Mzc3ODYsImV4cCI6MjA2MjIxMzc4Nn0.RsThz3p8-YEgQ3aiMECb4SLQPvnu7OTLExVR7bnVYIk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);